apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 031195399649.dkr.ecr.us-west-1.amazonaws.com/backend:25-88e71eb

        ports:
        - containerPort: 3000